<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from "vue";

// 16x16 canvas, one #rrggbb string per pixel (row-major: index = y*16 + x).
const SIZE = 16;
const pixels = ref(new Array(SIZE * SIZE).fill("#000000"));
const currentColor = ref("#ff3b30");
const arrayName = ref("MY_ART");
const copied = ref(false);

// A few quick-pick swatches so kids aren't stuck in the color dialog.
const swatches = [
  "#ff3b30", "#ff9500", "#ffcc00", "#34c759", "#00c7be",
  "#007aff", "#5856d6", "#af52de", "#ffffff", "#000000",
];

let isPainting = false;

function paint(index, erase) {
  pixels.value[index] = erase ? "#000000" : currentColor.value;
}

function onDown(index, event) {
  isPainting = true;
  paint(index, event.button === 2); // right-click erases
}

function onEnter(index, event) {
  if (!isPainting) return;
  // event.buttons: 1 = left held, 2 = right held
  paint(index, event.buttons === 2);
}

function stopPainting() {
  isPainting = false;
}

function clearAll() {
  pixels.value = new Array(SIZE * SIZE).fill("#000000");
}

function fillAll() {
  pixels.value = new Array(SIZE * SIZE).fill(currentColor.value);
}

function toRRGGBB(hex) {
  return hex.replace("#", "").toUpperCase();
}

const safeName = computed(() => {
  const cleaned = arrayName.value.replace(/[^A-Za-z0-9_]/g, "");
  return cleaned || "MY_ART";
});

const snippet = computed(() => {
  const name = safeName.value;
  const rows = [];
  for (let y = 0; y < SIZE; y++) {
    const row = [];
    for (let x = 0; x < SIZE; x++) row.push("0x" + toRRGGBB(pixels.value[y * SIZE + x]));
    rows.push("  " + row.join(", ") + ",");
  }
  return (
    "// Pixel art — generated by the HW Lab drawing tool. Paste above setup().\n" +
    `const uint32_t ${name}[256] = {\n${rows.join("\n")}\n};\n\n` +
    "// Then in setup() (after lightGrid.begin) or a command handler:\n" +
    `//   lightGrid.drawFrame(${name});\n` +
    "//   renderMatrix();"
  );
});

async function copySnippet() {
  try {
    await navigator.clipboard.writeText(snippet.value);
    copied.value = true;
    window.setTimeout(() => (copied.value = false), 1500);
  } catch {
    copied.value = false;
  }
}

onMounted(() => window.addEventListener("mouseup", stopPainting));
onBeforeUnmount(() => window.removeEventListener("mouseup", stopPainting));
</script>

<template>
  <section class="studio">
    <div class="canvas-col">
      <h2>Pixel Art (16×16)</h2>
      <p class="hint">
        Click or drag to paint. Right-click to erase. Then copy the code into
        <code>xiao.ino</code>.
      </p>

      <div class="grid" @contextmenu.prevent>
        <div
          v-for="(color, index) in pixels"
          :key="index"
          class="cell"
          :style="{ background: color }"
          @mousedown="onDown(index, $event)"
          @mouseenter="onEnter(index, $event)"
        />
      </div>

      <div class="tools">
        <label class="picker">
          Color
          <input v-model="currentColor" type="color" />
        </label>
        <div class="swatches">
          <button
            v-for="c in swatches"
            :key="c"
            class="swatch"
            :class="{ active: c === currentColor }"
            :style="{ background: c }"
            :aria-label="c"
            @click="currentColor = c"
          />
        </div>
        <button type="button" @click="fillAll">Fill</button>
        <button type="button" @click="clearAll">Clear</button>
      </div>
    </div>

    <div class="code-col">
      <div class="code-header">
        <label class="name">
          Array name
          <input v-model="arrayName" type="text" spellcheck="false" />
        </label>
        <button type="button" class="copy" @click="copySnippet">
          {{ copied ? "Copied!" : "Copy code" }}
        </button>
      </div>
      <pre class="snippet">{{ snippet }}</pre>
    </div>
  </section>
</template>

<style scoped>
.studio {
  display: grid;
  grid-template-columns: auto 1fr;
  gap: 24px;
  align-items: start;
}

.hint {
  color: #555;
  margin: 0 0 12px;
}
.hint code {
  background: #eee;
  border-radius: 4px;
  padding: 1px 5px;
}

.grid {
  display: grid;
  grid-template-columns: repeat(16, 22px);
  grid-template-rows: repeat(16, 22px);
  gap: 1px;
  background: #ccc;
  border: 2px solid #999;
  width: max-content;
  user-select: none;
}
.cell {
  width: 22px;
  height: 22px;
  cursor: crosshair;
}

.tools {
  align-items: center;
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  margin-top: 14px;
}
.picker {
  align-items: center;
  display: flex;
  font-weight: 600;
  gap: 6px;
}
.picker input {
  height: 32px;
  width: 44px;
}
.swatches {
  display: flex;
  gap: 4px;
}
.swatch {
  border: 2px solid #ddd;
  border-radius: 6px;
  cursor: pointer;
  height: 26px;
  width: 26px;
}
.swatch.active {
  border-color: #2563eb;
}
.tools button {
  background: #2563eb;
  border: none;
  border-radius: 8px;
  color: #fff;
  cursor: pointer;
  font-weight: 600;
  padding: 8px 14px;
}

.code-header {
  align-items: center;
  display: flex;
  gap: 12px;
  margin-bottom: 8px;
}
.name {
  align-items: center;
  display: flex;
  font-weight: 600;
  gap: 6px;
}
.name input {
  border: 1px solid #ddd;
  border-radius: 6px;
  font-family: ui-monospace, monospace;
  padding: 6px 8px;
}
.copy {
  background: #2563eb;
  border: none;
  border-radius: 8px;
  color: #fff;
  cursor: pointer;
  font-weight: 600;
  margin-left: auto;
  padding: 8px 16px;
}
.snippet {
  background: #1e1e1e;
  border-radius: 8px;
  color: #d4d4d4;
  font-size: 12px;
  margin: 0;
  max-height: 480px;
  overflow: auto;
  padding: 12px;
  white-space: pre;
}
</style>
